### ISSUE TITLE
 zal-config.yaml error

### ISSUE THREAD

**Issue by owelinux** [devopyio/zabbix-alertmanager#53]
time="2019-10-09T12:38:16+08:00" level=fatal msg="can't read the config file: zal-config.yaml: yaml: unmarshal errors:\n  line 2: cannot unmarshal !!str `INFRA` into []string\n  line 14: cannot unmarshal !!str `WEBTEAM` into []string"

config:
 - name: infrahost
   hostGroups: INFRA
   tag: prometheus
   deploymentStatus: 0
   itemDefaultApplication: prometheus
   itemDefaultHistory: 5d
   itemDefaultTrends: 5d
   itemDefaultTrapperHosts: 0.0.0.0/0
   triggerTags:
    INFRA: ""
   alertsDir: ./infra

 - name: webhost
   hostGroups: WEBTEAM
   tag: prometheus
   deploymentStatus: 0
   itemDefaultApplication: prometheus
   itemDefaultHistory: 5d
   itemDefaultTrends: 5d
   itemDefaultTrapperHosts: 0.0.0.0/0
   triggerTags:
    WEBT: ""
   alertsDir: ./web

**Comment by devopsjonas** [comment]
this looks like misconfiguration, triggerTags can't be empty.
