### ISSUE TITLE
Failed in creating triggers

### ISSUE THREAD

**Issue by owelinux** [devopyio/zabbix-alertmanager#54]
time="2019-10-09T15:51:43+08:00" level=info msg="loaded hosts configuration from 'zal-config.yaml'"
time="2019-10-09T15:51:43+08:00" level=info msg="Prometheus Rules for host - infra loaded: 9"
time="2019-10-09T15:51:44+08:00" level=info msg="HOSTGROUPS, total: 1, new or updated: 0"
time="2019-10-09T15:51:44+08:00" level=info msg="HOSTS, total: 1, new or updated: 0"
time="2019-10-09T15:51:44+08:00" level=info msg="APPLICATIONS, total: 1, new or updated: 0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.poddown, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.podrestart, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.nodestatuserror, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.daemonsetunavailable, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.pod_all_cpu_usage, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.nodeunschedulable, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.jobfailed, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.pod_all_memory_usage, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="GetItemsByState = State: New, Key: prometheus.pod_all_network_receive_usage, Applications: map[prometheus:{}]"
time="2019-10-09T15:51:44+08:00" level=info msg="ITEMS, total: 10, new or updated: 9"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.nodeunschedulable.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.nodestatuserror.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.jobfailed.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.pod_all_network_receive_usage.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.poddown.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.podrestart.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.daemonsetunavailable.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.pod_all_cpu_usage.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="GetTriggersByState = State: New, Expression: {infra:prometheus.pod_all_memory_usage.last()}<>0"
time="2019-10-09T15:51:44+08:00" level=info msg="TRIGGERS, total: 9, new or updated: 9"
time="2019-10-09T15:51:45+08:00" level=fatal msg="error provisioning zabbix items: error applying changes: Failed in creating triggers: invalid character '<' looking for beginning of value"

**Comment by devopsjonas** [comment]
looks like you have bad config, please provide your zal configuration.
