### ISSUE TITLE
404 on pages with tutorials

### ISSUE THREAD

**Issue by virtualb0x** [devopyio/zabbix-alertmanager#81]
Hello!

I'm new to prometheus alert manager and I have to integrate one with zabbix.

But I can't read the tutorials inside github dir, they go to 404 error
__
I do not understand what the file   

    --hosts-path=HOSTS-PATH    Path to resolver to host mapping file.

has to be like?

And also - can i change standart port of zabbix server, not 10051 one for zabbix trapper?

**Comment by devopsjonas** [comment]
hey, thanks for taking an interest, for commercial help and support inquiries please contact info@devopy.io
